const express = require("express");
const { productGet,productPost, addProduct, searchProduct, viewProduct, UpdateProduct, editProduct, DeleteProduct, softDeleteProduct, addtoCart,Basket, DeleteCart } = require("../controllers/productControllers");
const { authenticated ,adminOnly} = require("../middlewares/middlware");
const { logout } = require("../controllers/authControllers");
const productRouter = express.Router();
productRouter.use(authenticated);
productRouter.get("/products",productGet);

productRouter.post("/products",productPost);
productRouter.get("/addproduct",adminOnly,addProduct);
productRouter.get("/find-products",adminOnly,searchProduct);
productRouter.get("/viewProduct/:id",viewProduct);
productRouter.get("/logout",logout);
productRouter.post("/updateproduct/:id",UpdateProduct);
productRouter.get("/editproduct/:id",adminOnly,editProduct);
productRouter.delete("/productdelete/:id",softDeleteProduct);
productRouter.post("/deleteproduct/:id",DeleteProduct);
productRouter.post("/add-to-cart",addtoCart);
productRouter.get("/basket",Basket);
productRouter.post("/deletecart",DeleteCart);
module.exports = productRouter;
